---
title: "Chapter 1--Arrests"
output: html_notebook
---

Merge CA, ND, and OH marijuana votes with arrest data

```{r}


California_Marijuana_Data <- read.csv(
  "C:/Users/carol/Downloads/California_Marijuana.csv",
  header = TRUE,
  check.names = TRUE
)

str(California_Marijuana_Data)

California_Marijuana_Data <- California_Marijuana_Data %>%
  rename("County" = "ï..County")

CA_2006_2016<- read.csv(
  "C:/Users/carol/Downloads/CA_2006_2016.csv",
  header = TRUE,
  check.names = TRUE
)


CA_2006_2016 <- merge(CA_2006_2016, California_Marijuana_Data, by="County")

write.csv(CA_2006_2016,  "C:/Users/carol/Downloads/CA_2006_2016.csv", row.names=FALSE)

#NORTH DAKOTA 

ND_Marijuana_Data <- read.csv(
  "C:/Users/carol/Downloads/ND_Marijuana.csv",
  header = TRUE,
  check.names = TRUE
)

str(ND_Marijuana_Data)

ND_Marijuana_Data <- ND_Marijuana_Data %>%
  rename("County" = "ï..County")

ND_2012_2020 <- read.csv(
  "C:/Users/carol/Downloads/ND_2012_2020.csv",
  header = TRUE,
  check.names = TRUE
)

str(ND_2012_2020)

ND_2012_2020 <- ND_2012_2020 %>%
  rename("County" = "ctnm")

ND_2012_2020 <- merge(ND_2012_2020, ND_Marijuana_Data, by="County")

write.csv(ND_2012_2020,  "C:/Users/carol/Downloads/ND_2012_2020.csv", row.names=FALSE)

#OHIO

OH_Marijuana_Data <- read.csv(
  "C:/Users/carol/Downloads/OH_Marijuana.csv",
  header = TRUE,
  check.names = TRUE
)

str(OH_Marijuana_Data)

OH_Marijuana_Data <- OH_Marijuana_Data %>%
  rename("County" = "ï..County")

OH_2010_2020 <- read.csv(
  "C:/Users/carol/Downloads/OH_2010_2020.csv",
  header = TRUE,
  check.names = TRUE
)

str(OH_2010_2020)

OH_2010_2020 <- OH_2010_2020 %>%
  rename("County" = "ctnm")

OH_2010_2020 <- merge(OH_2010_2020, OH_Marijuana_Data, by="County")

write.csv(OH_2010_2020,  "C:/Users/carol/Downloads/OH_2010_2020.csv", row.names=FALSE)

```
Load all clean data

```{r Loading Clean Data}

CA_2006_2016<- read.csv(
  "C:/Users/carol/Downloads/CA_2006_2016.csv",
  header = TRUE,
  check.names = F
)

AZ_2006_2020<- read.csv(
  "C:/Users/carol/Downloads/AZ_2006_2020.csv",
  header = TRUE,
  check.names = F
)

CO_2000_2010 <- read.csv(
  "C:/Users/carol/Downloads/CO_2000_2010.csv",
  header = TRUE,
  check.names = F
)

OH_2010_2020 <- read.csv(
  "C:/Users/carol/Downloads/OH_2010_2020.csv",
  header = TRUE,
  check.names = F
)

ND_2012_2020<- read.csv(
  "C:/Users/carol/Downloads/ND_2012_2020.csv",
  header = TRUE,
  check.names = F
)

#note that OH has no counties that voted YES so it's kind of useless. 


```

Let's run some regressions. CALIFORNIA

```{r California}

colnames(CA_2006_2016)[2]<-"year"  
colnames(CA_2006_2016)[25]<-"Approved_Prop"  

CA_before_2006_yes_vote <- CA_2006_2016 %>%
  filter(year <= 2010 ) %>%
  filter(Approved_Prop == "Y") %>%
  drop_na()


CA_before_2006_no_vote <- CA_2006_2016 %>%
  filter(year <= 2010 ) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()


CA_after_2006_yes_vote <- CA_2006_2016 %>%
  filter(year > 2010 ) %>% 
  filter(Approved_Prop == "Y") %>%
  drop_na()
 

CA_after_2006_no_vote <- CA_2006_2016 %>%
  filter(year > 2010 ) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()

#take 2009 and 2011, do paired t-test for yes and no. Then get the change in arrest rates from 09 to '11. Those changes are a pooled T-test. Check to see if variance is equal. this will lead to a treatment effects regression. doc on t.test function will give a lot. look at pooled and paired.

CA_2009_yes_vote <- CA_2006_2016 %>%
  filter(year == 2009 ) %>% 
  filter(Approved_Prop == "Y") %>%
  drop_na()
 

CA_2011_yes_vote <- CA_2006_2016 %>%
  filter(year == 2011 ) %>%
  filter(Approved_Prop == "Y") %>%
  drop_na()

CA_2009_no_vote <- CA_2006_2016 %>%
  filter(year == 2009 ) %>% 
  filter(Approved_Prop == "N") %>%
  drop_na()
 

CA_2011_no_vote <- CA_2006_2016 %>%
  filter(year == 2011 ) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()

anti_join(CA_2009_yes_vote, CA_2011_yes_vote, by="County")
anti_join(CA_2009_no_vote, CA_2011_no_vote, by="County")

CA_2009_yes_vote <- CA_2009_yes_vote[-c(1), ]

CA_yes_vote_paired_t <- t.test(CA_2009_yes_vote$rc_rate, CA_2011_yes_vote$rc_rate, paired = T) %>%
  add_significance()

CA_no_vote_paired_t <- t.test(CA_2009_no_vote$rc_rate, CA_2011_no_vote$rc_rate, paired = T)


CA_yes_and_no_vote_paired_t <- 
  rbind(CA_yes_vote_paired_t, CA_no_vote_paired_t) %>%
  gt() %>%
  tab_row_group(label = "Group 1", rows = 1) %>%
  tab_row_group(label = "Group 2", rows = 2)


CA_yes_vote_pooled_t <- t.test(CA_2009_yes_vote$rc_rate, CA_2011_yes_vote$rc_rate, var.equal = T)
CA_no_vote_pooled_t  <- t.test(CA_2009_no_vote$rc_rate, CA_2011_no_vote$rc_rate, var.equal = T)

#take all counties in 2011 and do a test to see if theres a difference between the yeses and nos. With a p.value of .64, this says now before the vote of decriminalization, arrests rates were the same. After P.value is much lower so we are closer to being able to reject the null

CA_2009 <-
  CA_2006_2016 %>%
  filter(year == 2009)

CA_all_counties <- t.test(CA_2009_yes_vote$rc_rate, CA_2009_no_vote$rc_rate, var.equal = T)

CA_all_counties_after_vote <- t.test(CA_2011_yes_vote$rc_rate, CA_2011_no_vote$rc_rate, var.equal = T)

CA_all_counties_after_vote

#California

CA_2006_2016 <-
  CA_2006_2016 %>%
  mutate(rc_tot = rc_tot %>% 
           str_remove_all(",") %>%
           as.numeric())


wilcox.test(CA_2006_2016 %>%
              filter(year <= 2010) %>%
            select(rc_tot) %>%
              unlist , CA_2006_2016 %>%
  filter(year > 2010) %>%
  select(rc_tot) %>%
  unlist)

CA_2006_2016 %>%
  ggplot(aes(x = year, y = rc_tot, group = year)) + geom_boxplot()


#yes vs no counties without year consideration 

wilcox.test(CA_2006_2016 %>%
              filter(Approved_Prop == "Y") %>%
            select(rc_tot) %>%
              unlist , CA_2006_2016 %>%
  filter(Approved_Prop == "N") %>%
  select(rc_tot) %>%
  unlist)

#yes v no counties comparing after 2010 prop

wilcox.test(CA_2006_2016 %>%
              filter(Approved_Prop == "Y" , year > 2010 ) %>%
            select(rc_tot) %>%
              unlist , CA_2006_2016 %>%
  filter(Approved_Prop == "N", year > 2010 ) %>%
  select(rc_tot) %>%
  unlist)

#there was a preexisting difference in arrest rates from those counties and then they voted yes or no, and then there wasn't a difference. 

wilcox.test(CA_2006_2016 %>%
              filter(Approved_Prop == "Y" , year <= 2010 ) %>%
            select(rc_tot) %>%
              unlist , CA_2006_2016 %>%
  filter(Approved_Prop == "N", year <= 2010 ) %>%
  select(rc_tot) %>%
  unlist)

#first is significant for year <= 2010, second is significant for approved.prop and third is significant for both together (how the yes, no question agumented whether before or after 2010). 

med2way(data = CA_2006_2016 , rc_tot ~ factor(I(year <= 2010)) + factor(Approved_Prop))

CA_2006_2016 %>%
  group_by(year <= 2010 , Approved_Prop) %>%
  summarize(rc_tot_med = median(rc_tot))

#cor.test for correlations between numerics. Generally don't consider percent yes. 

ggplot(CA_2006_2016, aes(x = Percent.Yes , y = rc_rate)) + geom_point()

#cor.test for race differences. The two rates between black and white arrest rates are 

cor.test(CA_2006_2016$w_rate , CA_2006_2016$b_rate)

CA_2006_2016 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  med1way(formula = rate ~ race)

CA_2006_2016 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  group_by(race , year > 2010 , Approved_Prop) %>%
  summarize(rate_med = median(na.rm = T , rate))

```

Let's run some regressions. ARIZONA

```{r Arizona}
colnames(AZ_2006_2020)[25]<-"Approved_Prop" 
colnames(AZ_2006_2020)[29]<-"Percent_Yes"  

#count counties

AZ_2016_yes_votes <- AZ_2006_2020 %>%
  filter(year == 2016) %>%
  filter(Approved_Prop == "Yes") 

n_distinct(AZ_2006_2020$ctnm)

#median and mean change before and after referendum

AZ_before_2016 <- AZ_2006_2020 %>% 
  filter(year <= 2016)

AZ_after_2016 <- AZ_2006_2020 %>% 
  filter(year < 2020, year > 2016)

AZ_summary_before <- summarize(AZ_before_2016, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

AZ_summary_after <- summarize(AZ_after_2016, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

wilcox.test(AZ_2006_2020 %>%
              filter(year <= 2016) %>%
            select(rc_rate) %>%
              unlist , AZ_2006_2020 %>%
  filter(year < 2020, year > 2016) %>%
  select(rc_rate) %>%
  unlist)

AZ_meanandmedianbeforeandafter <- cbind(AZ_summary_before, AZ_summary_after)

stargazer(AZ_meanandmedianbeforeandafter, type = "latex")

#do it based on prop approval 

AZ_before_2016_yes_vote <- AZ_2006_2020 %>%
  filter(year <= 2016 ) %>%
  filter(Approved_Prop == "Yes") 


AZ_before_2016_no_vote <- AZ_2006_2020 %>%
  filter(year <= 2016 ) %>%
  filter(Approved_Prop == "No") 


AZ_after_2016_yes_vote <- AZ_2006_2020 %>%
  filter(year < 2020, year > 2016 ) %>% 
  filter(Approved_Prop == "Yes") 
 
AZ_after_2016_no_vote <- AZ_2006_2020 %>%
  filter(year < 2020, year > 2016 ) %>%
  filter(Approved_Prop == "No") 

summary_AZ_yes_before <- summarize(AZ_before_2016_yes_vote,  mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summary_AZ_yes_after <- summarize(AZ_after_2016_yes_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summary_AZ_no_before <- summarize(AZ_before_2016_no_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summary_AZ_no_after <- summarize(AZ_after_2016_no_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

AZ_Before_and_After_Y_and_N <- cbind(summary_AZ_yes_before, summary_AZ_yes_after, summary_AZ_no_before, summary_AZ_no_after)

stargazer(AZ_Before_and_After_Y_and_N , type = "latex")

t.test(AZ_before_2016_yes_vote$rc_rate, AZ_after_2016_yes_vote$rc_rate, paired = F)

t.test(AZ_before_2016_no_vote$rc_rate , AZ_after_2016_no_vote$rc_rate, paired = F)

#take 2015 and 2017, do paired t-test for yes and no. Then get the change in arrest rates from '15 to '17. Those changes are a pooled T-test. Check to see if variance is equal. this will lead to a treatment effects regression. doc on t.test function will give a lot. look at pooled and paired.

AZ_2015_yes_vote <- AZ_2006_2020 %>%
  filter(year == 2015) %>%
  filter(Approved_Prop == "Yes") 

AZ_2017_yes_vote <- AZ_2006_2020 %>%
  filter(year == 2017 ) %>%
  filter(Approved_Prop == "Yes")

AZ_2015_no_vote <- AZ_2006_2020 %>%
  filter(year == 2015 ) %>% 
  filter(Approved_Prop == "No")

AZ_2017_no_vote <- AZ_2006_2020 %>%
  filter(year == 2017 ) %>%
  filter(Approved_Prop == "No") 


anti_join(AZ_2015_yes_vote, AZ_2017_yes_vote, by="ctnm")
anti_join(AZ_2017_no_vote, AZ_2015_no_vote, by = "ctnm")

AZ_2017_no_vote <- AZ_2017_no_vote[-c(5), ]

summarize(AZ_2017_no_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summarize(AZ_2017_yes_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summarize(AZ_2015_no_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

summarize(AZ_2015_yes_vote, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

t.test(AZ_2015_yes_vote$rc_rate, AZ_2017_yes_vote$rc_rate, paired = T)
t.test(AZ_2015_no_vote$rc_rate, AZ_2017_no_vote$rc_rate, paired = T)


AZ_2006_2020 <- AZ_2006_2020 %>%
  mutate(year = year %>%
           as.factor) %>%
  mutate(Approved_Prop = Approved_Prop %>%
           as.factor)

AZ_boxPlot_Ch1_1 <- AZ_2006_2020 %>%
  filter(year %in% c(2015 , 2017)) %>%
  ggplot(aes(y = rc_rate, x = year)) + 
  geom_boxplot(aes(color = Approved_Prop)) + 
  facet_wrap(~Approved_Prop) +
  geom_signif(comparisons = list(c("2015" , "2017")) , 
    map_signif_level = TRUE,
    textsize = 6,
    step_increase = .1
  ) +
  ylim(0, 1500) +
  labs(
    x = "Year",
    y = "Arrest rates – all races, per 100,000",
    title = "Arizona Arrest Rates Before and After Referendum",
    caption = "Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1"
  ) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) 

ggsave(AZ_boxPlot_Ch1_1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/AZ_boxPlot_Ch1_1.png")


#this one is probably not helpful. think about how a pooled t.test might be beneficial/if it is. 
t.test(AZ_2015_yes_vote$rc_rate, AZ_2017_yes_vote$rc_rate, var.equal = T)
t.test(AZ_2015_no_vote$rc_rate, AZ_2017_no_vote$rc_rate, var.equal = T)

AZ_2006_2020 <-
  AZ_2006_2020 %>%
  mutate(rc_tot = rc_tot %>% 
           str_remove_all(",") %>%
           as.numeric())


wilcox.test(AZ_2006_2020 %>%
              filter(year <= 2016) %>%
            select(rc_tot) %>%
              unlist , AZ_2006_2020 %>%
  filter(year > 2016) %>%
  select(rc_tot) %>%
  unlist)

AZ_2006_2020 %>%
  ggplot(aes(x = year, y = rc_tot, group = year)) + geom_boxplot()

#yes vs no counties without year consideration 

wilcox.test(AZ_2006_2020 %>%
              filter(Approved_Prop == "Yes") %>%
            select(rc_tot) %>%
              unlist , AZ_2006_2020 %>%
  filter(Approved_Prop == "No") %>%
  select(rc_tot) %>%
  unlist)

#yes v no counties comparing after 2016 prop

wilcox.test(AZ_2006_2020 %>%
              filter(Approved_Prop == "Yes" , year > 2016 , year < 2020) %>%
            select(rc_tot) %>%
              unlist , AZ_2006_2020 %>%
  filter(Approved_Prop == "No", year > 2016 , year < 2020 ) %>%
  select(rc_tot) %>%
  unlist)


#there was a preexisting difference in arrest rates from those counties and then they voted yes or no, and then there wasn't a difference. 


wilcox.test(AZ_2006_2020 %>%
              filter(Approved_Prop == "Yes" , year <= 2016 ) %>%
            select(rc_rate) %>%
              unlist , AZ_2006_2020 %>%
  filter(Approved_Prop == "No", year <= 2016 ) %>%
  select(rc_rate) %>%
  unlist)

wilcox.test(AZ_2006_2020 %>%
              filter(Approved_Prop == "Yes" , year < 2020, year > 2016 ) %>%
            select(rc_rate) %>%
              unlist , AZ_2006_2020 %>%
  filter(Approved_Prop == "No", year < 2020, year > 2016 ) %>%
  select(rc_rate) %>%
  unlist)

AZ_2006_2020 %>%
  ggplot(aes(x = year, y = rc_rate, group = year)) + geom_boxplot()

#ask JONATHAN how to do this one. 

AZ_boxPlot3_Ch1 <- AZ_2006_2020 %>%
  filter(year <= 2016 ,  2020 > year > 2016) %>%
  ggplot(aes(y = rc_rate, x = Approved_Prop)) + 
  geom_boxplot() + 
  facet_wrap(~year) +
  geom_signif(comparisons = list(c("Yes" , "No")) , 
    map_signif_level = TRUE,
    textsize = 6,
    step_increase = .1
  ) +
  ylim(0, 2000) +
  labs(
    x = "Approved Proposition",
    y = "Arrest rates – all races, per 100,000",
    title = "Arizona Arrest Rates Before and After Referendum",
    caption = "Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1"
  ) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) 

ggsave(AZ_boxPlot_Ch1_1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/AZ_boxPlot3_Ch1.png")

#first is significant for year <= 2016, second is significant for approved.prop and third is significant for both together (how the yes, no question augmented whether before or after 2016). 

med2way(data = AZ_2006_2020 , rc_tot ~ factor(I(year <= 2016)) + factor(Approved_Prop))

med2way(data = AZ_2006_2020 , rc_rate ~ factor(I(year <= 2016)) + factor(Approved_Prop))

AZ_2006_2020 %>%
  group_by(year <= 2016 , Approved_Prop) %>%
  summarize(rc_tot_med = median(rc_tot))

AZ_2006_2020 %>%
  group_by(year <= 2016 , Approved_Prop) %>%
  summarize(rc_rate_med = median(rc_rate))

#cor.test for correlations between numerics. Generally don't consider percent yes. 

ggplot(AZ_2006_2020, aes(x = Percent_Yes , y = rc_rate)) + geom_point()

#cor.test for race differences. The two rates between black and white arrest rates are 

cor.test(AZ_2006_2020$w_rate , AZ_2006_2020$b_rate)

AZ_2006_2020 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  med1way(formula = rate ~ race)

AZ_2006_2020 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  group_by(race , year > 2016 , Approved_Prop) %>%
  summarize(rate_med = median(na.rm = T , rate))

AZ_boxplot2_ch1 <- AZ_2006_2020 %>%
  ggplot(aes(x = year, y = rc_rate, group = year)) + geom_boxplot() +
  labs(
    x = "Year",
    y = "Arrest rates – all races, per 100,000",
    title = "Arizona Arrest Rates by Year")

ggsave(AZ_boxplot2_ch1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/AZ_boxplot2_ch1.png")

```


Let's run some regressions. COLORADO

```{r Colorado}
colnames(CO_2000_2010)[25]<-"Approved_Prop" 
colnames(CO_2000_2010)[29]<-"Percent_Yes"  

CO_2000_2010 %>%
  filter(Approved_Prop == "Y") %>%
  filter(year == 2006) %>%
  nrow()

CO_2000_2010 %>%
  filter(Approved_Prop == "N") %>%
  filter(year == 2006) %>%
  nrow()

CO_2000_2010 <- CO_2000_2010 %>%
  mutate(year = year %>%
           as.factor) %>%
  mutate(Approved_Prop = Approved_Prop %>%
           as.factor)

# Create new data frames for each year
CO_before_2006_yes_vote <- CO_2000_2010 %>%
  filter(year <= 2006) %>%
  filter(Approved_Prop == "Y") %>%
  drop_na()



CO_before_2006_no_vote <- CO_2000_2010 %>%
  filter(year <= 2006) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()


CO_after_2006_yes_vote <- CO_2000_2010 %>%
  filter(year > 2006) %>% 
  filter(Approved_Prop == "Y") %>%
  drop_na()
 

CO_after_2006_no_vote <- CO_2000_2010 %>%
  filter(year > 2006) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()


#paired t-test

#t.test(CO_before_2006_yes_vote$rc_rate, CO_after_2006_yes_vote$rc_rate, paired = F)
#t.test(CO_before_2006_no_vote$rc_rate , CO_after_2006_no_vote$rc_rate, paired = F)

#take 2005 and 2007, do paired t-test for yes and no. Then get the change in arrest rates from '05 to '07. Those changes are a pooled T-test. Check to see if variance is equal. this will lead to a treatment effects regression. doc on t.test function will give a lot. look at pooled and paired.

CO_2005_yes_vote <- CO_2000_2010 %>%
  filter(year == 2005) %>%
  filter(Approved_Prop == "Y") 

CO_2007_yes_vote <- CO_2000_2010 %>%
  filter(year == 2007 ) %>%
  filter(Approved_Prop == "Y")

CO_2005_no_vote <- CO_2000_2010 %>%
  filter(year == 2005 ) %>% 
  filter(Approved_Prop == "N")

CO_2007_no_vote <- CO_2000_2010 %>%
  filter(year == 2007 ) %>%
  filter(Approved_Prop == "N") 

nrow(CO_2005_no_vote)
nrow(CO_2007_no_vote)

anti_join(CO_2005_yes_vote, CO_2007_yes_vote, by="County")
anti_join(CO_2007_no_vote, CO_2005_no_vote, by = "County")

CO_2005_yes_vote <- CO_2005_yes_vote[-c(12), ]
CO_2005_no_vote <- CO_2005_no_vote[-c(5, 9, 10, 12, 25, 35, 40), ]
CO_2007_no_vote <- CO_2007_no_vote[-c(23), ]

t.test(CO_2005_yes_vote$rc_rate, CO_2007_yes_vote$rc_rate, paired = T)
t.test(CO_2005_no_vote$rc_rate, CO_2007_no_vote$rc_rate, paired = T)


t.test(before_2006_yes$rc_rate, after_2006_yes$rc_rate, var.equal = T)
t.test(before_2006_no$rc_rate, after_2006_no$rc_rate, var.equal = T)


CO_boxPlot_Ch1_1 <- CO_2000_2010 %>%
  filter(year %in% c(2005 , 2007)) %>%
  ggplot(aes(y = rc_rate, x = year)) + 
  geom_boxplot(aes(color = Approved_Prop)) + 
  facet_wrap(~Approved_Prop) +
  geom_signif(comparisons = list(c("2005" , "2007")) , 
    map_signif_level = TRUE,
    textsize = 6,
    step_increase = .1
  ) +
  ylim(0, 800) +
  labs(
    x = "Year",
    y = "Arrest rates – all races, per 100,000",
    title = "Colorado Arrest Rates Before and After Referendum",
    caption = "Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1"
  ) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) 

ggsave(CO_boxPlot_Ch1_1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/CO_boxPlot_Ch1_1.png")

# 

CO_2000_2010 <-
  CO_2000_2010 %>%
  mutate(rc_tot = rc_tot %>% 
           str_remove_all(",") %>%
           as.numeric(), 
         year = year %>%
           as.numeric)

class(CO_2000_2010$year)

wilcox.test(CO_2000_2010 %>%
              filter(year <= 2006) %>%
            select(rc_tot) %>%
              unlist , CO_2000_2010 %>%
  filter(year > 2006) %>%
  select(rc_tot) %>%
  unlist)

CO_wilcox_test <- wilcox.test(CO_2000_2010 %>%
              filter(year <= 2006) %>%
            select(rc_rate) %>%
              unlist , CO_2000_2010 %>%
  filter(year > 2006) %>%
  select(rc_rate) %>%
  unlist)


before_2006 <- CO_2000_2010 %>% 
  filter(year <= 2006)
after_2006 <- CO_2000_2010 %>% 
  filter(year > 2006)

CO_summary_before <- summarize(before_2006, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_summary_after <- summarize(after_2006, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_meanandmedianbeforeandafter <- cbind(CO_summary_before, CO_summary_after)

stargazer(CO_meanandmedianbeforeandafter, type = "latex")

before_2006_yes <- CO_2000_2010 %>% 
  filter(year <= 2006) %>%
  filter(Approved_Prop == "Y")

summarize(before_2006_yes, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

after_2006_yes <- CO_2000_2010 %>% 
  filter(year > 2006) %>%
  filter(Approved_Prop == "Y")

before_2006_no <- CO_2000_2010 %>% 
  filter(year <= 2006) %>%
  filter(Approved_Prop == "N")

after_2006_no <- CO_2000_2010 %>% 
  filter(year > 2006) %>%
  filter(Approved_Prop == "N")

CO_summary_before_yes <- summarize(before_2006_yes, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_summary_after_yes <- summarize(after_2006_yes, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_summary_before_no <- summarize(before_2006_no, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_summary_after_no <- summarize(after_2006_no, mean_rc_rate = mean(rc_rate) , median_rc_rate = median(rc_rate))

CO_Summary_Before_and_after_Y_and_N <- cbind(CO_summary_before_yes, CO_summary_after_yes, CO_summary_before_no, CO_summary_after_no)

kbl(CO_Summary_Before_and_after_Y_and_N, booktabs =T)
  

stargazer(CO_Summary_Before_and_after_Y_and_N, type = "latex")

CO_2000_2010 %>%
  ggplot(aes(x = year, y = rc_tot, group = year)) + geom_boxplot()

CO_boxplot2_ch1 <- CO_2000_2010 %>%
  ggplot(aes(x = year, y = rc_rate, group = year)) + geom_boxplot() +
  labs(
    x = "Year",
    y = "Arrest rates – all races, per 100,000",
    title = "Colorado Arrest Rates by Year")

ggsave(CO_boxplot2_ch1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/CO_boxplot2_ch1.png")

#yes vs no counties without year consideration 

wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "Y") %>%
            select(rc_tot) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N") %>%
  select(rc_tot) %>%
  unlist)


wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "Y") %>%
            select(rc_rate) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N") %>%
  select(rc_rate) %>%
  unlist)

#yes v no counties comparing after 2006 prop

wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "Y" , year > 2006 ) %>%
            select(rc_tot) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N", year > 2006 ) %>%
  select(rc_tot) %>%
  unlist)

wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "Y" , year > 2006 ) %>%
            select(rc_rate) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N", year > 2006 ) %>%
  select(rc_rate) %>%
  unlist)

#FIGURE OUT VISUALIZING THIS WITH JONATHAN

CO_before_yes_and_no <- t.test(before_2006_yes$rc_rate, before_2006_no$rc_rate, var.equal = FALSE)

CO_after_yes_and_no <-t.test(after_2006_yes$rc_rate, after_2006_no$rc_rate, var.equal = FALSE)

pandoc.table(CO_before_yes_and_no, caption = "Colorado Before Referendum", style = "rmarkdown", highlight = "signif", split.cells = 30)

pandoc.table(CO_after_yes_and_no, caption = "Colorado Before Referendum", style = "rmarkdown", highlight = "signif", split.cells = 30)

  
#there was a preexisting difference in arrest rates from those counties and then they voted yes or no, and then there wasn't a difference. 

wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "Y" , year <= 2006 ) %>%
            select(rc_tot) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N", year <= 2006 ) %>%
  select(rc_rate) %>%
  unlist)

wilcox.test(CO_2000_2010 %>%
              filter(Approved_Prop == "N" , year <= 2006 ) %>%
            select(rc_rate) %>%
              unlist , CO_2000_2010 %>%
  filter(Approved_Prop == "N", year > 2006 ) %>%
  select(rc_rate) %>%
  unlist)

#first is significant for year <= 2006, second is significant for approved.prop and third is significant for both together (how the yes, no question augmented whether before or after 2006). 

med2way(data = CO_2000_2010 , rc_tot ~ factor(I(year <= 2006)) + factor(Approved_Prop))

med2way(data = CO_2000_2010 , rc_rate ~ factor(I(year <= 2006)) + factor(Approved_Prop))

CO_2000_2010 %>%
  group_by(year <= 2006 , Approved_Prop) %>%
  summarize(rc_tot_med = median(rc_tot))

CO_2000_2010 %>%
  group_by(year <= 2006 , Approved_Prop) %>%
  summarize(rc_rate_med = median(rc_rate))

#cor.test for correlations between numerics. Generally don't consider percent yes. 

ggplot(CO_2000_2010, aes(x = Percent_Yes , y = rc_rate)) + geom_point()

#cor.test for race differences. The two rates between black and white arrest rates are 

cor.test(CO_2000_2010$w_rate , CO_2000_2010$b_rate)

CO_table_1_Ch1 <- CO_2000_2010 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  med1way(formula = rate ~ race) 


write.table(CO_table_1_Ch1, file = "C:/Users/carol/Desktop/Dissertation Code/Dissertation-Code/Images/CO_table_1_Ch1.png")



CO_2000_2010 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  group_by(race , year > 2006 , Approved_Prop) %>%
  summarize(rate_med = median(na.rm = T , rate))

```

Let's run some regressions. North Dakota

```{r North Dakota}
colnames(ND_2012_2020)[25]<-"Approved_Prop" 
colnames(ND_2012_2020)[29]<-"Percent_Yes"  
colnames(ND_2012_2020)[2]<-"year"  

ND_before_2006_yes_vote <- ND_2012_2020 %>%
  filter(year <= 2018) %>%
  filter(Approved_Prop == "Y") %>%
  drop_na()


ND_before_2006_no_vote <- ND_2012_2020 %>%
  filter(year <= 2018) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()


ND_after_2006_yes_vote <- ND_2012_2020 %>%
  filter(year > 2018) %>% 
  filter(Approved_Prop == "Y") %>%
  drop_na()
 

ND_after_2006_no_vote <- ND_2012_2020 %>%
  filter(year > 2018) %>%
  filter(Approved_Prop == "N") %>%
  drop_na()

t.test(ND_before_2006_yes_vote$rc_rate, ND_after_2006_yes_vote$rc_rate, paired = F)
t.test(ND_before_2006_no_vote$rc_rate , ND_after_2006_no_vote$rc_rate, paired = F)


#take 2017 and 2019, do paired t-test for yes and no. Then get the change in arrest rates from '17 to '19. Those changes are a pooled T-test. Check to see if variance is equal. this will lead to a treatment effects regression. doc on t.test function will give a lot. look at pooled and paired.

ND_2017_yes_vote <- ND_2012_2020 %>%
  filter(year == 2017) %>%
  filter(Approved_Prop == "Y") 

ND_2019_yes_vote <- ND_2012_2020 %>%
  filter(year == 2019 ) %>%
  filter(Approved_Prop == "Y")

ND_2017_no_vote <- ND_2012_2020 %>%
  filter(year == 2017 ) %>% 
  filter(Approved_Prop == "N")

ND_2019_no_vote <- ND_2012_2020 %>%
  filter(year == 2019 ) %>%
  filter(Approved_Prop == "N") 

nrow(ND_2017_no_vote)
nrow(ND_2019_no_vote)

anti_join(ND_2017_yes_vote, ND_2019_yes_vote, by="County")
anti_join(CO_2007_no_vote, CO_2005_no_vote, by = "County")

ND_2017_yes_vote <- ND_2017_yes_vote[-c(1, 3), ]
CO_2007_no_vote <- CO_2007_no_vote[-c(23), ]

t.test(ND_2017_yes_vote$rc_rate, ND_2019_yes_vote$rc_rate, paired = T)
t.test(ND_2017_no_vote$rc_rate, ND_2019_no_vote$rc_rate, paired = T)

#note I CAN PUT THESE LOST VALUES BACK IN THE CALCULATION

ND_2017_yes_vote <- ND_2012_2020 %>%
  filter(year == 2017) %>%
  filter(Approved_Prop == "Y") 

ND_2019_yes_vote <- ND_2012_2020 %>%
  filter(year == 2019 ) %>%
  filter(Approved_Prop == "Y")

ND_2017_no_vote <- ND_2012_2020 %>%
  filter(year == 2017 ) %>% 
  filter(Approved_Prop == "N")

ND_2019_no_vote <- ND_2012_2020 %>%
  filter(year == 2019 ) %>%
  filter(Approved_Prop == "N") 

summarise(ND_2017_yes_vote, Mean_2017_Yes_RC_Rate = mean(rc_rate) , Median_2017_Yes_RC_rate = median(rc_rate))
summarise(ND_2017_no_vote, Mean_2017_No_RC_Rate = mean(rc_rate) , Median_2017_No_RC_Rate = median(rc_rate))
summarise(ND_2019_yes_vote, Mean_2019_Yes_RC_Rate = mean(rc_rate) , Median_2019_Yes_RC_rate = median(rc_rate))
summarise(ND_2019_no_vote, Mean_2019_No_RC_Rate = mean(rc_rate) , Median_2019_No_RC_Rate = median(rc_rate))

###
ND_2012_2020 <-
  ND_2012_2020 %>%
  mutate(rc_tot = rc_tot %>% 
           str_remove_all(",") %>%
           as.numeric())


wilcox.test(ND_2012_2020 %>%
              filter(year <= 2018) %>%
            select(rc_tot) %>%
              unlist , ND_2012_2020 %>%
  filter(year > 2018) %>%
  select(rc_tot) %>%
  unlist)

wilcox.test(ND_2012_2020 %>%
              filter(year <= 2018) %>%
            select(rc_rate) %>%
              unlist , ND_2012_2020 %>%
  filter(year > 2018) %>%
  select(rc_rate) %>%
  unlist)

ND_2012_2020 %>%
  ggplot(aes(x = year, y = rc_tot, group = year)) + geom_boxplot()

ND_2012_2020 %>%
  ggplot(aes(x = year, y = rc_rate, group = year)) + geom_boxplot()

#yes vs no counties without year consideration 

wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y") %>%
            select(rc_tot) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N") %>%
  select(rc_tot) %>%
  unlist)


wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y") %>%
            select(rc_rate) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N") %>%
  select(rc_rate) %>%
  unlist)

#yes v no counties comparing after 2016 prop

wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y" , year > 2018 ) %>%
            select(rc_tot) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N", year > 2018 ) %>%
  select(rc_tot) %>%
  unlist)

wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y" , year > 2018 ) %>%
            select(rc_rate) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N", year > 2018 ) %>%
  select(rc_rate) %>%
  unlist)

#there was a preexisting difference in arrest rates from those counties and then they voted yes or no, and then there wasn't a difference. 

wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y" , year <= 2018 ) %>%
            select(rc_tot) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N", year <= 2018 ) %>%
  select(rc_tot) %>%
  unlist)

wilcox.test(ND_2012_2020 %>%
              filter(Approved_Prop == "Y" , year <= 2018 ) %>%
            select(rc_rate) %>%
              unlist , ND_2012_2020 %>%
  filter(Approved_Prop == "N", year <= 2018 ) %>%
  select(rc_rate) %>%
  unlist)

#first is significant for year <= 2006, second is significant for approved.prop and third is significant for both together (how the yes, no question augmented whether before or after 2006). 

med2way(data = ND_2012_2020 , rc_tot ~ factor(I(year <= 2018)) + factor(Approved_Prop))

med2way(data = ND_2012_2020 , rc_rate ~ factor(I(year <= 2018)) + factor(Approved_Prop))

ND_2012_2020 %>%
  group_by(year <= 2018 , Approved_Prop) %>%
  summarize(rc_tot_med = median(rc_tot))

ND_2012_2020 %>%
  group_by(year <= 2018 , Approved_Prop) %>%
  summarize(rc_rate_med = median(rc_rate))

#cor.test for correlations between numerics. Generally don't consider percent yes. 

ggplot(ND_2012_2020, aes(x = Percent_Yes , y = rc_rate)) + geom_point()

#cor.test for race differences. The two rates between black and white arrest rates are 

cor.test(ND_2012_2020$w_rate , ND_2012_2020$b_rate)

ND_2012_2020 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  med1way(formula = rate ~ race)

ND_2012_2020 %>%
  pivot_longer(cols = c("w_rate", "b_rate" , "i_rate" , "a_rate"
  ) , names_to = "race" , values_to = "rate") %>%
  group_by(race , year > 2018 , Approved_Prop) %>%
  summarize(rate_med = median(na.rm = T , rate))

```